# Generated by Django 5.2.4 on 2025-07-23 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0002_portfolio_profile_image_timelineevent_event_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
    ]
