# Generated by Django 5.2.4 on 2025-07-23 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='event_image',
            field=models.ImageField(blank=True, null=True, upload_to='event_images/'),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='video_url',
            field=models.URLField(blank=True, help_text='Optional: A link to a YouTube or Vimeo video.', null=True),
        ),
    ]
