# Generated by Django 5.2.4 on 2025-07-27 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0003_portfolio_email_portfolio_linkedin_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='background_image',
            field=models.ImageField(blank=True, help_text='Optional. A high-resolution background image for your portfolio page.', null=True, upload_to='backgrounds/'),
        ),
    ]
